/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/auth`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/admin-dashboard` | `/admin-dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/admin-orders` | `/admin-orders`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/admin-pricing` | `/admin-pricing`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/admin-riders` | `/admin-riders`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/admin-users` | `/admin-users`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/customer-home` | `/customer-home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/customer-profile` | `/customer-profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/rider-home` | `/rider-home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/rider-profile` | `/rider-profile`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/auth`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/admin-dashboard` | `/admin-dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/admin-orders` | `/admin-orders`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/admin-pricing` | `/admin-pricing`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/admin-riders` | `/admin-riders`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/admin-users` | `/admin-users`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/customer-home` | `/customer-home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/customer-profile` | `/customer-profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/rider-home` | `/rider-home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/rider-profile` | `/rider-profile`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/auth${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/admin-dashboard${`?${string}` | `#${string}` | ''}` | `/admin-dashboard${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/admin-orders${`?${string}` | `#${string}` | ''}` | `/admin-orders${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/admin-pricing${`?${string}` | `#${string}` | ''}` | `/admin-pricing${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/admin-riders${`?${string}` | `#${string}` | ''}` | `/admin-riders${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/admin-users${`?${string}` | `#${string}` | ''}` | `/admin-users${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/customer-home${`?${string}` | `#${string}` | ''}` | `/customer-home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/customer-profile${`?${string}` | `#${string}` | ''}` | `/customer-profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/rider-home${`?${string}` | `#${string}` | ''}` | `/rider-home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/rider-profile${`?${string}` | `#${string}` | ''}` | `/rider-profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/auth`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/admin-dashboard` | `/admin-dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/admin-orders` | `/admin-orders`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/admin-pricing` | `/admin-pricing`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/admin-riders` | `/admin-riders`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/admin-users` | `/admin-users`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/customer-home` | `/customer-home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/customer-profile` | `/customer-profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/rider-home` | `/rider-home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/rider-profile` | `/rider-profile`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
